# Frontend Dockerfile
FROM nginx:latest
RUN apt-get update && apt-get install -y git
RUN git clone https://github.com/rumid111/Multi-tier-application.git /tmp/repo
WORKDIR /usr/share/nginx/html
RUN cp /tmp/repo/index.html ./ && cp /tmp/repo/styles.css ./
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
