# Backend Dockerfile
FROM python:3.9-slim
RUN apt-get update && apt-get install -y git
RUN git clone https://github.com/rumid111/Multi-tier-application.git /tmp/repo
WORKDIR /app
# Adjusted paths to match flat structure
RUN cp /tmp/repo/app.py ./ && cp /tmp/repo/requirements.txt ./
RUN pip install -r requirements.txt
EXPOSE 5000
CMD ["python", "app.py"]

