# Frontend Dockerfile
FROM nginx:alpine
RUN apk add --no-cache git
RUN git clone https://github.com/rumid111/Multi-tier-application.git /tmp/repo
WORKDIR /usr/share/nginx/html
# Adjusted paths to match flat structure
RUN cp /tmp/repo/index.html ./ && cp /tmp/repo/style.css ./
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
